---
title: "FinalRuleEDA"
author: "Chenery Lowe"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

# set working directory
setwd("C:/Users/clowe7/OneDrive - Stanford/Final Rule Analysis") #***You'll want to change the working directory to reflect the location where your files are stored

# install packages
library(dplyr)
library(readxl)
library(tidyverse)
library(ggplot2)
library(tidyverse)
library(arsenal)
library(coin)
library(psych)
library(corrplot)
library(car)
library(stargazer)
library(likert)

# load data file ***Make sure that the file is in the working directory that you set above; otherwise, you will need to specify the full pathway
data_labels<-read.csv("102 Survey_AssessingGeneticCoun-ForDataAnalysis_DATA_LABELS_2024-02-06_1407 (1).csv")

data<-read.csv("AssessingGeneticCoun-ForDataAnalysis_DATA_2024-02-25_1458.csv")

#Analysis 1a: The existence of direct contact, institutional policies, 
#dept/division/workgroup policies, blocking policies, and changes to pt portal 
#policies are associated with less perceived disruption to workflow, less 
#perceived pt harms, and more perceived pt benefits.

# Recode policies as 0 if it does not exist or not sure, NA if NA, and 1 if anything else
data$policies_dept_1a <- ifelse(data$policies_dept %in% c(4, 5), 0,
                                 ifelse(data$policies_dept == 6, NA,
                                        ifelse(data$policies_dept %in% c(1, 2, 3), 1, data$policies_dept)
                                       ))

# Recoding the 'data$policies_institutional' variable
data$policies_institutional_1a <- ifelse(data$policies_instituitional %in% c(4, 5), 0,
                                  ifelse(data$policies_instituitional == 6, NA,
                                         ifelse(data$policies_instituitional %in% c(1, 2, 3), 1, data$policies_instituitional)
                                        ))

# Recoding the 'data$policies_portal' variable
data$policies_portal_1a <- ifelse(data$policies_portal %in% c(4, 5), 0,
                                ifelse(data$policies_portal == 6, NA,
                                       ifelse(data$policies_portal %in% c(1, 2, 3), 1, data$policies_portal)
                                      ))


#Analysis1b: The involvement of GCs in these policies is associated with less 
#perceived disruption to workflow, less perceived pt harms, and more perceived 
#pt benefits.
# recode variables for analysis 1b (GC involved in policy vs. not involved vs. no known policy)
# Recoding policies_institutional
data$policies_institutional_1b <- ifelse(data$policies_instituitional == 1, 2,
                                  ifelse(data$policies_instituitional == 2, 1,
                                         ifelse(data$policies_instituitional == 3, 1,
                                                ifelse(data$policies_instituitional %in% c(4, 5), 0,
                                                       ifelse(data$policies_instituitional == 6, NA, data$policies_institutional)
                                                      ))))

# Recoding policies_dept
data$policies_dept_1b <- ifelse(data$policies_dept == 1, 2,
                          ifelse(data$policies_dept == 2, 1,
                                 ifelse(data$policies_dept == 3, 1,
                                       ifelse(data$policies_dept %in% c(4, 5), 0,
                                              ifelse(data$policies_dept == 6, NA, data$policies_dept)
                                             ))))

# Recoding policies_portal
data$policies_portal_1b <- ifelse(data$policies_portal == 1, 2,
                            ifelse(data$policies_portal == 2, 1,
                                   ifelse(data$policies_portal == 3, 1,
                                         ifelse(data$policies_portal %in% c(4, 5), 0,
                                                ifelse(data$policies_portal == 6, NA, data$policies_portal)
                                               ))))

# recode as factor
data$policies_dept_1b <- as.factor(data$policies_dept_1b)
data$policies_institutional_1b <- as.factor(data$policies_institutional_1b)
data$policies_portal_1b <- as.factor(data$policies_portal_1b)

#perceived harms
data$pt_reaction <- ifelse(data$pt_reaction == 6, NA, data$pt_reaction)
data$pt_understand <- ifelse(data$pt_understand == 6, NA, data$pt_understand)
data$pt_contact <- ifelse(data$pt_contact == 6, NA, data$pt_contact)


#perceived benefits
data$pt_empower <- ifelse(data$pt_empower == 6, NA, data$pt_empower)
data$pt_processing <- ifelse(data$pt_processing == 6, NA, data$pt_processing)
data$pt_assurance <- ifelse(data$pt_assurance == 6, NA, data$pt_assurance)
data$pt_action <- ifelse(data$pt_action == 6, NA, data$pt_action)
data$pt_share <- ifelse(data$pt_share == 6, NA, data$pt_share)

#workplace effects
data$checking <- ifelse(data$checking == 6, NA, data$checking)
data$timing <- ifelse(data$timing == 6, NA, data$timing)
data$communications <- ifelse(data$communications == 6, NA, data$communications)
data$change <- ifelse(data$change == 6, NA, data$change)
data$coordination_dept <- ifelse(data$coordination_dept == 6, NA, data$coordination_dept)
data$coordination_other <- ifelse(data$coordination_other == 6, NA, data$coordination_other)
data$sending_results <- ifelse(data$sending_results == 6, NA, data$sending_results)


# DEMOGRAPHIC VARIABLES

# years of GC experience as ordered factor variable
data$demo_years <- factor(data$demo_years, levels = 1:8, ordered = TRUE)

# age as ordered factor variable
data$demo_age <- factor(data$demo_age, levels = 1:11, ordered = TRUE)

# position as ordered factor
data$position <- factor(data$position, 
                                 levels = 1:3, 
                                 labels = c("Direct patient care",
                                            "Non-direct patient care",
                                            "Mixed position"))

# ordering provider
data$ordering_provider <- factor(data$ordering_provider, 
                                 levels = 1:4, 
                                 labels = c("Yes. I place and sign orders as the provider of record",
                                            "No. I place the order but am not listed as the ordering provider",
                                            "No. I cannot place or sign orders",
                                            "No. I do not order in my role"))

# region
data$demo_list <- factor(data$demo_list, 
                                 levels = 1:6, 
                                 labels = c("Region 1 (CT, MA, ME, NH, RI, VT, CNMaritime Provinces)",
                                            "Region 2 (DC, DE, MD, NJ, NY, PA, VA, WV,PR, VI, Quebec)",
                                            "Region 3 (AL, FL, GA, KY, LA, MS, NC, SC,TN)",
                                            "Region 4 (AR, IA, IL, IN, KS, MI, MN, MO,ND, NE, OH, OK, SD, WI, Ontario)",
                                            "Region 5 (AZ, CO, MT, NM, TX, UT, WY, Alberta, Manitoba, Sask.)",
                                            "Region 6 (AK, CA, HI, ID, NV, OR, WA, British Columbia)"))


# convert race/ethnicity variables to factor
for (i in 1:8) {
  var_name <- paste0("demo_raceethnicity___", i)
  data[[var_name]] <- factor(data[[var_name]], 
                             levels = 0:1, 
                             labels = c("NA", "1"))
}



# Create a mapping for race categories
race_categories <- c("demo_raceethnicity___1", "demo_raceethnicity___2", "demo_raceethnicity___3", 
                     "demo_raceethnicity___4", "demo_raceethnicity___5", "demo_raceethnicity___6")

race_mapping <- setNames(c("African American or Black", 
                           "Native American/ Alaska Native/ First Nations/ Indigenous", 
                           "Asian", "Native Hawaiian/ Pacific Islander", 
                           "White", "Other"),
                         race_categories)


# Create the 'race' variable
data$race <- apply(data[race_categories], 1, function(x) {
  selected <- which(x == 1)
  selected_names <- names(selected)
  if(length(selected) > 1) {
    return("Multiple")
  } 
  else if(length(selected) == 1) {
    return(race_mapping[selected_names])
  } 
  else {
    return(NA)
  }
})

# Create the 'ethnicity' variable
data$ethnicity <- ifelse(data$demo_raceethnicity___7 == 1, "Non-Hispanic or -Latino",
                      ifelse(data$demo_raceethnicity___8 == 1, "Hispanic or Latino", NA))


#clean workplace setting variable
workplace_labels <- list(
  "Government organization or agency",
  "Hospital/Medical Facility- Academic Medical Center",
  "Hospital/Medical Facility- Public or Community Based Hospital (including FQHC)",
  "Hospital/Medical Facility- Private",
  "Insurance Company/Benefit Management Company",
  "Laboratory Commercial",
  "Not-For-Profit Organization (non-hospital)",
  "Private Practice",
  "Private Company-Biotechnology/ Research development, Digital Health/Software, Pharmaceutical",
  "Other")

# Create a matrix for the workplacesetting variable
workplace_matrix <- data.frame(data[ , grepl("^workplacesetting___", names(data))])


# Create the workplacesetting variable following your requirements
data$workplacesetting <- apply(workplace_matrix, 1, function(x) {
  indices <- which(x == 1)
  if(length(indices) > 1) {
    return("Multiple")
  } else if(length(indices) == 1) {
    return(workplace_labels[[indices]])
  } else {
    return("None")
  }
})

# Create the workplace_multiple variable
data$workplace_multiple <- apply(workplace_matrix, 1, function(x) {
  indices <- which(x == 1)
  if(length(indices) > 1) {
    return(paste(workplace_labels[indices], collapse = ","))
  } else {
    return(NA)
  }
})

# clean gender variable
demo_gender_labels <- list(
  "Man",
  "Non-binary",
  "Transgender",
  "Woman",
  "Other",
  "Unsure/questioning",
  "Prefer not to say")


# Create a matrix for the demo_genders
demo_gender_matrix <- data.frame(data[ , grepl("^demo_gender___", names(data))])


# Create the demo_gender variable following your requirements
data$demo_gender <- apply(demo_gender_matrix, 1, function(x) {
  indices <- which(x == 1)
  if(length(indices) > 1) {
    return("Multiple")
  } else if(length(indices) == 1) {
    return(demo_gender_labels[[indices]])
  } else {
    return("None")
  }
})

# Create the demo_gender_multiple variable
data$demo_gender_multiple <- apply(demo_gender_matrix, 1, function(x) {
  indices <- which(x == 1)
  if(length(indices) > 1) {
    return(paste(demo_gender_labels[indices], collapse = ","))
  } else {
    return(NA)
  }
})


# combine "no" variables for ordering provider
data$ordering_provider_r <- dplyr::recode(data$ordering_provider, 
                                  "No. I place the order but am not listed as the ordering provider" = "Non-ordering provider", 
                                  "No. I cannot place or sign orders" = "Non-ordering provider",
                                  "No. I do not order in my role" = "Non-ordering provider",
                                  .default = "Ordering provider")

# set up labels for the participant characteristics table ***This list isn't complete - add the rest of the variable names here
labs<- c(demo_age = "Age",
         demo_list = "Region",
         demo_years = "Years of experience as a practicing GC"
)

```


## Factor analysis for outcome variables

### Perceived benefits
```{r, include=FALSE}
# subset perceived benefits variables
ben <- data %>%
  select(pt_empower:pt_share) %>%
  mutate_all(as.numeric)

# Now omit NA values
ben <- na.omit(ben)

# correlation matrix
datamatrix<-cor(ben)
corrplot::corrplot(datamatrix, method = "number")

# analyze factorability of the data
X<-ben

#Kaiser-Meyer Olkin
KMO(r=cor(X))

#Bartlett's test of sphericity
cortest.bartlett(X)
det(cor(X))

# scree plot
library(ggplot2)
fafitfree <- fa(ben,nfactors = ncol(X), rotate = "none")
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)
ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot", 
        subtitle = "(Based on the unreduced correlation matrix)")

parallel<-fa.parallel(X)

# 1 factor
factanal_1 <- factanal(X, factors=1, scores = c("regression"), rotation = "varimax")
print(factanal_1)

# 2 factors
factanal_2 <- factanal(X, factors=2, scores = c("regression"), rotation = "varimax")
print(factanal_2)

# check internal consistency of benefits variables (Cronbach's alpha)

# correlation matrix
datamatrix<-cor(ben)
corrplot::corrplot(datamatrix, method = "number")

# Cronbach's alpha, allowing negatively correlated items to be reversed
psych::alpha(X, check.keys = TRUE)

# create benefits score
data$benefits <- rowSums(data[,c("pt_empower", "pt_processing", "pt_assurance", "pt_action", "pt_share")], na.rm = TRUE)


```
### Perceived harms
```{r, include=FALSE}
# subset perceived harms variables
harm <- data %>%
  select(pt_reaction:pt_contact) %>%
  mutate_all(as.numeric)

# Omit NA values
harm <- na.omit(harm)

# correlation matrix
datamatrix<-cor(harm)
corrplot::corrplot(datamatrix, method = "number")

# analyze factorability of the data
X<-harm

#Kaiser-Meyer Olkin
KMO(r=cor(X))

#Bartlett's test of sphericity
cortest.bartlett(X)
det(cor(X))

# scree plot
library(ggplot2)
fafitfree <- fa(harm,nfactors = ncol(X), rotate = "none")
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)
ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot", 
        subtitle = "(Based on the unreduced correlation matrix)")

parallel<-fa.parallel(X)

# 1 factor
factanal_1 <- factanal(X, factors=1, scores = c("regression"), rotation = "varimax")
print(factanal_1)

# check internal consistency of variables (Cronbach's alpha)

# correlation matrix
datamatrix<-cor(harm)
corrplot::corrplot(datamatrix, method = "number")

# Cronbach's alpha, allowing negatively correlated items to be reversed
psych::alpha(X, check.keys = TRUE)

# create harms score
data$harms <- rowSums(data[,c("pt_reaction", "pt_understand", "pt_contact")], na.rm = TRUE)

```

### Perceived impact on workflow
```{r, include=FALSE}
# subset perceived workflow impact variables
work <- data %>%
  select(checking:coordination_other) %>%
  mutate_all(as.numeric)

# Omit NA values
work <- na.omit(work)

# correlation matrix
datamatrix<-cor(work)
corrplot::corrplot(datamatrix, method = "number")

# analyze factorability of the data
X<-work

#Kaiser-Meyer Olkin
KMO(r=cor(X))

#Bartlett's test of sphericity
cortest.bartlett(X)
det(cor(X))

# scree plot
library(ggplot2)
fafitfree <- fa(work,nfactors = ncol(X), rotate = "none")
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)
ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot", 
        subtitle = "(Based on the unreduced correlation matrix)")

parallel<-fa.parallel(X)

# 1 factor
factanal_1 <- factanal(X, factors=1, scores = c("regression"), rotation = "varimax")
print(factanal_1)

# 2 factors
factanal_2 <- factanal(X, factors=2, scores = c("regression"), rotation = "varimax")
print(factanal_2)

# check internal consistency of variables (Cronbach's alpha)

# correlation matrix
datamatrix<-cor(work)
corrplot::corrplot(datamatrix, method = "number")

# Cronbach's alpha, allowing negatively correlated items to be reversed
psych::alpha(X, check.keys = TRUE)

# create workflow impact score - dropping last item
data$work <- rowSums(data[,c("checking", "timing", "communications", "change", "coordination_dept", "coordination_other")], na.rm = FALSE)

```

# convert policies variables to factor
```{r, include=FALSE}
var_names <- names(data)[which(names(data) == "policies_instituitional"):which(names(data) == "policies_portal")]

# Loop through each variable name
for (var in var_names) {

  # Create a temporary variable leaving as numeric
  temp_var <- data[[var]]

  # Recode level 6 as NA
  temp_var[temp_var == 6] <- NA

  # Create the new variable as a factor
  data[paste(var, "_r", sep="")] <- factor(temp_var)
}

# Create a factor level
factor_levels <- setNames(c("This exists and a GC was involved",
                            "This exists and a GC was NOT involved",
                            "This exists and I don't know if a GC was involved",
                            "This DOES NOT exist",
                            "I am not sure",
                            "Not applicable at my workplace"),
                          1:6)

# Get the column names
col_names <- names(data)

# Define the range of column names
start_col <- which(col_names == "policies_instituitional_r")
end_col <- which(col_names == "policies_portal_r")
selected_cols <- col_names[start_col:end_col]


# Convert all relevant variables
data <- data %>%
  mutate(across(selected_cols, ~ fct_explicit_na(factor(., levels = names(factor_levels), labels = factor_levels), na_level = "Not applicable at my workplace")))



```

# Summary table overall
```{r, results='asis', echo=FALSE}
# select the relevant variables
desc<-data%>%
  select(ordering_provider, demo_years, position, workplacesetting, demo_list,
         race, ethnicity, demo_age, demo_gender,
          policies_instituitional_r:policies_portal_r, benefits, harms, work
         )

# variable labels
labels(desc)<-labs

#create formula
myvars<-names(desc)
tmp<-formulize(X=myvars[2:(ncol(desc))])

summary(tableby(tmp, data = desc,
              digits = 2L))


```

# Summary table by ordering provider
```{r, results='asis', echo=FALSE}
# select the relevant variables
desc<-data%>%
  select(ordering_provider_r, ordering_provider, demo_years, position, workplacesetting, demo_list,
         race, ethnicity, demo_age, demo_gender,
          policies_instituitional_r:policies_portal_r, benefits, harms, work
         )

# Replace spaces with underscores and remove special characters
names(desc) <- gsub(" ", "_", names(desc))
names(desc) <- gsub("[^[:alnum:]_]", "", names(desc))


# Check the new column names
print(names(desc))

# After the column names have been cleaned up, you can run your code again:

tmp <- formulize("ordering_provider_r", myvars[2:(ncol(desc))])

# variable labels
labels(desc)<-labs

#create formula
myvars<-names(desc)
tmp<-formulize("ordering_provider_r", myvars[2:(ncol(desc))])

summary(tableby(tmp, data = desc,
              digits = 2L), pfootnote = TRUE)


```


# Figure
## 1a. workflow impact

```{r, echo=FALSE, results='asis'}

#Figure 1a. workflow impact
work.data<-data%>%select(ordering_provider_r, 
  checking:sending_results)

# Recode
# Define the mapping for the recoding
factor_levels <- c("1" = "Strongly disagree", 
                   "2" = "Disagree", 
                   "3" = "Neither agree nor disagree", 
                   "4" = "Agree", 
                   "5" = "Strongly agree", 
                   "6" = NA)

# Define a list of old and new names
name_mapping <- list("checking" = "need to check the electronic medical record and/or my email more frequently",
                     "timing" = "have less time to review results before discussing with a patient",
                     "communications" = "receive increased patient communications prior to my results review and disclosure",
                     "change" = "changed my workflow to comply with the Final Rule",
                     "coordination_dept" = "face coordination of care challenges within my department (example, results going to a geneticist first delaying my review of results)",
                     "coordination_other" = "face coordination of care challenges with providers outside of my department (example, patients seeing results and messaging non-ordering providers for interpretation before I can discuss",
                     "sending_results" = "have one less administrative task because results are sent to patients automatically",
                     "pt_reaction" = "could have strong emotional reactions when reviewing results/notes on their own",
                     "pt_understand" = "could misunderstand or misinterpret results",
                     "pt_contact" = "could contact the inappropriate party to discuss results (example: direct laboratory or non-ordering provider contact)",
                     "pt_knowledge" = "have more knowledge/context/questions at our disclosure session due to previous results review",
                     "pt_empower" = "are empowered due to direct access to their medicalrecords",
                     "pt_processing" = "have increased engagement due to time to emotionallyprocess results on their own before our conversation",
                     "pt_assurance" = "could have earlier reassurance about results",
                     "pt_action" = "could take earlier action on results",
                     "pt_share" = "have easier access to share their results/chart with other providers without genetic counselor involvement")

# remove NA values
work.data <- na.omit(work.data)

# Apply recoding 
work.data <- work.data %>%
   mutate(across(-ordering_provider_r, ~factor(., levels = names(factor_levels), labels = factor_levels)))
# Rename variables 
for (i in seq_along(name_mapping)) {
  names(work.data)[names(work.data) == names(name_mapping)[i]] <- name_mapping[[i]]
}

# Create likert object, grouped by 'ordering_provider_r'
likert_obj <- likert(work.data[ , -1], grouping = work.data$ordering_provider_r)

# Plot
fig1a <- plot(likert_obj) +  
  scale_fill_manual(values = RColorBrewer::brewer.pal(n=6,"RdYlBu"), 
                    breaks = c("Strongly disagree", "Disagree", "Neither agree nor disagree", "Agree", "Strongly agree")) +
  guides(fill = guide_legend(title="")) + 
  labs(title="Workflow impact")

# create table version

# select the relevant variables
desc<-work.data

# Replace spaces with underscores and remove special characters
names(desc) <- gsub(" ", "_", names(desc))
names(desc) <- gsub("[^[:alnum:]_]", "", names(desc))

# variable labels
labels(desc)<-labs

#create formula
myvars<-names(desc)
tmp<-formulize("ordering_provider_r", myvars[2:(ncol(desc))])

summary(tableby(tmp, data = desc,
              digits = 2L), pfootnote = TRUE)


```
## 1b. harms
```{r, echo=FALSE,results='asis'}
# Add 'ordering_provider_r' to the selected columns
harm.data <- data %>%
   select(ordering_provider_r, pt_reaction:pt_contact)

# remove NA values
harm.data <- na.omit(harm.data)

# Apply recoding 
harm.data <- harm.data %>%
   mutate(across(-ordering_provider_r, ~factor(., levels = names(factor_levels), labels = factor_levels)))
# Rename variables 
for (i in seq_along(name_mapping)) {
  names(harm.data)[names(harm.data) == names(name_mapping)[i]] <- name_mapping[[i]]
}

# Create likert object, grouped by 'ordering_provider_r'
likert_obj <- likert(harm.data[ , -1], grouping = harm.data$ordering_provider_r)

# Plot
fig1b <- plot(likert_obj) +  
  scale_fill_manual(values = RColorBrewer::brewer.pal(n=6,"RdYlBu"), 
                    breaks = c("Strongly disagree", "Disagree", "Neither agree nor disagree", "Agree", "Strongly agree")) +
  guides(fill = guide_legend(title="")) + 
  labs(title="Harms")

# create table version
# select the relevant variables
desc<-harm.data

# Replace spaces with underscores and remove special characters
names(desc) <- gsub(" ", "_", names(desc))
names(desc) <- gsub("[^[:alnum:]_]", "", names(desc))

# variable labels
labels(desc)<-labs

#create formula
myvars<-names(desc)
tmp<-formulize("ordering_provider_r", myvars[2:(ncol(desc))])

summary(tableby(tmp, data = desc,
              digits = 2L), pfootnote = TRUE)


```

## 1c. benefits
```{r, echo=FALSE, results='asis'}
# Add 'ordering_provider_r' to the selected columns
ben.data <- data %>%
   select(ordering_provider_r, pt_knowledge:pt_share)

# remove NA values
ben.data <- na.omit(ben.data)

# Apply recoding 
ben.data <- ben.data %>%
   mutate(across(-ordering_provider_r, ~factor(., levels = names(factor_levels), labels = factor_levels)))
# Rename variables 
for (i in seq_along(name_mapping)) {
  names(ben.data)[names(ben.data) == names(name_mapping)[i]] <- name_mapping[[i]]
}

# Create likert object, grouped by 'ordering_provider_r'
likert_obj <- likert(ben.data[ , -1], grouping = ben.data$ordering_provider_r)

# Plot
fig1c <- plot(likert_obj) +  
  scale_fill_manual(values = RColorBrewer::brewer.pal(n=6,"RdYlBu"), 
                    breaks = c("Strongly disagree", "Disagree", "Neither agree nor disagree", "Agree", "Strongly agree")) +
  guides(fill = guide_legend(title="")) + 
  labs(title="Benefits")

# create table version of the figure
# select the relevant variables
desc<-ben.data

# Replace spaces with underscores and remove special characters
names(desc) <- gsub(" ", "_", names(desc))
names(desc) <- gsub("[^[:alnum:]_]", "", names(desc))

# variable labels
labels(desc)<-labs

#create formula
myvars<-names(desc)
tmp<-formulize("ordering_provider_r", myvars[2:(ncol(desc))])

summary(tableby(tmp, data = desc,
              digits = 2L), pfootnote = TRUE)
```

# put figure together
```{r}
library(ggpubr)
frplot<-ggarrange(fig1a, fig1b, fig1c,
                  labels=c("A","B", "C"),
                  ncol=3, nrow=1, common.legend = TRUE)

frplot

```





